version: "3"
services:
  mysql:
    image: mysql:latest
    volumes:
      - ".db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: callout
      MYSQL_USER: callout
      MYSQL_PASSWORD: password

  phpfpm:
    build: config/phpfpm
    container_name: callout_php
    depends_on:
      - mysql
    volumes:
      - "./app:/var/www/html"
      - "./vendor:/var/www/vendor"

  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:alpine
    volumes:
      - "./app:/var/www/html"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"
